version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_app
    volumes:
      - .:/var/www/html
    networks:
      - laravel

  webserver:
    image: php:8.1-apache
    container_name: apache_server
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - app
    networks:
      - laravel
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: medicus
      MYSQL_DATABASE: medicus
      MYSQL_USER:
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"
    networks:
      - laravel

networks:
  laravel:
    name: laravel
